FROM rust:latest

WORKDIR /app

COPY ./Rust/Script.rs .

RUN cargo init --bin

RUN mv Script.rs src/main.rs

RUN echo 'rand = "0.8"' >> Cargo.toml

RUN mkdir -p output

RUN cargo build --release

# Ejecutar el programa
CMD ["./target/release/app"]
